site_name: EnergiAI - Documentación
site_description: Guía técnica y documentación del proyecto EnergiAI
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: deep orange
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.superfences

nav:
  - Inicio: index.md
  - API: API.md
  - Arquitectura: ARCHITECTURE.md
  - Progreso: PROGRESS.md
  - Pruebas: test.md
