services:
  postgres:
    image: postgres:15-alpine
    container_name: energiai-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_contrasena
      POSTGRES_DB: energiai_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app-energi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-energi-ai
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/energiai_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=tu_contrasena
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata: