spring:
  application:
    name: backend
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://postgres:5432/energiai_db
    username: postgres
    password: tu_contrasena
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
  docker:
    compose:
      enabled: false

server:
  port: 8082